[package]
name = "treesize-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
csv = "1"
treesize-core = { path = "../core" }
crossbeam-channel = "0.5"
